services:
  postgres:
    container_name: js_postgres
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - 5431:5432

  redis:
    container_name: redis_js
    image: redis:alpine
    env_file:
      - .env
    ports:
      - 6378:6379